# github setting
safe: true
# source: <your pages repo>
# destination: <the build dir>
lsi: false
pygments: true
markdown: rdiscount

# my setting
author:
  name: ongaeshi
  email: ongaeshi0621@gmail.com

# navigation
navigation:
  - {id: index,      text: HOME}
  - {id: download,   text: Download}
  - {id: manual,     text: Manual}
  - {id: screenshot, text: ScreenShot}
  - {id: links,      text: Links}
