# github setting
safe: true
# source: <your pages repo>
# destination: <the build dir>
lsi: false
pygments: true
markdown: rdiscount

# navigation
navigation:
  - {id: index,      text: HOME}
  - {id: download,   text: Download}
  - {id: manual,     text: Manual}
  - {id: screenshot, text: ScreenShot}
  - {id: links,      text: Links}

# Google Analytics
tracking_code: UA-13136329-10